version: '4.0'

actions:
  extract_population_size:
    run: >
      sqlrunner:latest
        --output output/population_size.csv
        --dummy-data-file analysis/dummy.csv
        analysis/extract_population_size.sql
    outputs:
      moderately_sensitive:
        rows: output/population_size.csv
