version: '5.0'

actions:
  extract_population_size:
    run: >
      sqlrunner:v1
        --output output/population_size.csv
        --dummy-data-file analysis/dummy.csv
        analysis/extract_population_size_excl_t1oo.sql
    outputs:
      moderately_sensitive:
        rows: output/population_size.csv
  
  extract_population_size_including_t1oo:
    run: >
      sqlrunner:v1
        --output checks/population_size_including_t1oo.csv
        analysis/extract_population_size_incl_t1oo.sql
    outputs:
      moderately_sensitive:
        rows: checks/population_size_including_t1oo.csv

  extract_population_size_with_gp_activation_filtering:
    run: >
      sqlrunner:v1
        --output output/population_size_gp_activation_filtered.csv
        analysis/extract_population_size_excl_t1oo_gp_activation_filtered.sql
    outputs:
      moderately_sensitive:
        rows: output/population_size_gp_activation_filtered.csv

  extract_population_size_with_ehrql:
    run: >
      ehrql:v1
        generate-measures analysis/ehrql_extract_population_size.py
        --output checks/ehrql_population_size.csv
    outputs:
      moderately_sensitive:
        rows: checks/ehrql_population_size.csv

  extract_population_size_with_ehrql_including_gp_activation_filtering:
    run: >
      ehrql:v1
        generate-measures analysis/ehrql_extract_population_size.py
        --output checks/ehrql_population_size_with_gp_activation_filtering.csv
    outputs:
      moderately_sensitive:
        rows: checks/ehrql_population_size_with_gp_activation_filtering.csv

  # Temporary actions for debugging: extract patients without measures, and count
  debug_ehrql_extract_patients:
    run: >
      ehrql:v1
        generate-dataset analysis/debugging/ehrql_extract_population_exists.py
        --output debugging/ehrql_patients.csv
    outputs:
      highly_sensitive:
        rows: debugging/ehrql_patients.csv

  debug_count_patients:
    needs:
      - debug_ehrql_extract_patients
    run: >
      python:v2 analysis/debugging/count.py
    outputs:
      highly_sensitive:
        rows: debugging/ehrql_patients_count.csv
